title: LouieChewy.github.io
description: Project website
template:
  repo: louiechewy.github.io-template
  name: louiechewy.github.io
before:
  - type: createIssue
    title: Foot
    body: new-issue.md
steps: []
